// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomSystemParameters) DeepCopyInto(out *CustomSystemParameters) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomSystemParameters.
func (in *CustomSystemParameters) DeepCopy() *CustomSystemParameters {
	if in == nil {
		return nil
	}
	out := new(CustomSystemParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *System) DeepCopyInto(out *System) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new System.
func (in *System) DeepCopy() *System {
	if in == nil {
		return nil
	}
	out := new(System)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *System) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemList) DeepCopyInto(out *SystemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]System, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemList.
func (in *SystemList) DeepCopy() *SystemList {
	if in == nil {
		return nil
	}
	out := new(SystemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SystemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemObservation) DeepCopyInto(out *SystemObservation) {
	*out = *in
	if in.Authz != nil {
		in, out := &in.Authz, &out.Authz
		*out = new(V1AuthzConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Datasources != nil {
		in, out := &in.Datasources, &out.Datasources
		*out = make([]*V1DatasourceConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(V1DatasourceConfig)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make(map[string]V1AgentErrors, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(V1ObjectMeta)
		(*in).DeepCopyInto(*out)
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]*V1PolicyConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(V1PolicyConfig)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Tokens != nil {
		in, out := &in.Tokens, &out.Tokens
		*out = make([]*V1Token, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(V1Token)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Uninstall != nil {
		in, out := &in.Uninstall, &out.Uninstall
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make(map[string]V1SystemConfigWarnings, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemObservation.
func (in *SystemObservation) DeepCopy() *SystemObservation {
	if in == nil {
		return nil
	}
	out := new(SystemObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemParameters) DeepCopyInto(out *SystemParameters) {
	*out = *in
	in.CustomSystemParameters.DeepCopyInto(&out.CustomSystemParameters)
	if in.BundleRegistry != nil {
		in, out := &in.BundleRegistry, &out.BundleRegistry
		*out = new(V1BundleRegistryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DecisionMappings != nil {
		in, out := &in.DecisionMappings, &out.DecisionMappings
		*out = make(map[string]V1RuleDecisionMappings, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.DeploymentParameters != nil {
		in, out := &in.DeploymentParameters, &out.DeploymentParameters
		*out = new(V1SystemDeploymentParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
	if in.SourceControl != nil {
		in, out := &in.SourceControl, &out.SourceControl
		*out = new(V1SourceControlConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemParameters.
func (in *SystemParameters) DeepCopy() *SystemParameters {
	if in == nil {
		return nil
	}
	out := new(SystemParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemSpec) DeepCopyInto(out *SystemSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemSpec.
func (in *SystemSpec) DeepCopy() *SystemSpec {
	if in == nil {
		return nil
	}
	out := new(SystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemStatus) DeepCopyInto(out *SystemStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemStatus.
func (in *SystemStatus) DeepCopy() *SystemStatus {
	if in == nil {
		return nil
	}
	out := new(SystemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1AgentErrors) DeepCopyInto(out *V1AgentErrors) {
	*out = *in
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]*V1Status, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(V1Status)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Waiting != nil {
		in, out := &in.Waiting, &out.Waiting
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1AgentErrors.
func (in *V1AgentErrors) DeepCopy() *V1AgentErrors {
	if in == nil {
		return nil
	}
	out := new(V1AgentErrors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1AllowedMapping) DeepCopyInto(out *V1AllowedMapping) {
	*out = *in
	if in.Negated != nil {
		in, out := &in.Negated, &out.Negated
		*out = new(bool)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1AllowedMapping.
func (in *V1AllowedMapping) DeepCopy() *V1AllowedMapping {
	if in == nil {
		return nil
	}
	out := new(V1AllowedMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1AuthzConfig) DeepCopyInto(out *V1AuthzConfig) {
	*out = *in
	if in.RoleBindings != nil {
		in, out := &in.RoleBindings, &out.RoleBindings
		*out = make([]*V1RoleBindingConfig, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(V1RoleBindingConfig)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1AuthzConfig.
func (in *V1AuthzConfig) DeepCopy() *V1AuthzConfig {
	if in == nil {
		return nil
	}
	out := new(V1AuthzConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1BundleDistributionS3Config) DeepCopyInto(out *V1BundleDistributionS3Config) {
	*out = *in
	if in.Bucket != nil {
		in, out := &in.Bucket, &out.Bucket
		*out = new(string)
		**out = **in
	}
	if in.DiscoveryPath != nil {
		in, out := &in.DiscoveryPath, &out.DiscoveryPath
		*out = new(string)
		**out = **in
	}
	if in.OpaCredentials != nil {
		in, out := &in.OpaCredentials, &out.OpaCredentials
		*out = new(V1BundleDistributionS3ConfigOpaCredentials)
		(*in).DeepCopyInto(*out)
	}
	if in.PolicyPath != nil {
		in, out := &in.PolicyPath, &out.PolicyPath
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1BundleDistributionS3Config.
func (in *V1BundleDistributionS3Config) DeepCopy() *V1BundleDistributionS3Config {
	if in == nil {
		return nil
	}
	out := new(V1BundleDistributionS3Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1BundleDistributionS3ConfigOpaCredentials) DeepCopyInto(out *V1BundleDistributionS3ConfigOpaCredentials) {
	*out = *in
	if in.MetadataCredentials != nil {
		in, out := &in.MetadataCredentials, &out.MetadataCredentials
		*out = new(V1BundleDistributionS3ConfigOpaCredentialsMetadataCredentials)
		(*in).DeepCopyInto(*out)
	}
	if in.WebIdentityCredentials != nil {
		in, out := &in.WebIdentityCredentials, &out.WebIdentityCredentials
		*out = new(V1BundleDistributionS3ConfigOpaCredentialsWebIdentityCredentials)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1BundleDistributionS3ConfigOpaCredentials.
func (in *V1BundleDistributionS3ConfigOpaCredentials) DeepCopy() *V1BundleDistributionS3ConfigOpaCredentials {
	if in == nil {
		return nil
	}
	out := new(V1BundleDistributionS3ConfigOpaCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1BundleDistributionS3ConfigOpaCredentialsMetadataCredentials) DeepCopyInto(out *V1BundleDistributionS3ConfigOpaCredentialsMetadataCredentials) {
	*out = *in
	if in.AwsRegion != nil {
		in, out := &in.AwsRegion, &out.AwsRegion
		*out = new(string)
		**out = **in
	}
	if in.IamRole != nil {
		in, out := &in.IamRole, &out.IamRole
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1BundleDistributionS3ConfigOpaCredentialsMetadataCredentials.
func (in *V1BundleDistributionS3ConfigOpaCredentialsMetadataCredentials) DeepCopy() *V1BundleDistributionS3ConfigOpaCredentialsMetadataCredentials {
	if in == nil {
		return nil
	}
	out := new(V1BundleDistributionS3ConfigOpaCredentialsMetadataCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1BundleDistributionS3ConfigOpaCredentialsWebIdentityCredentials) DeepCopyInto(out *V1BundleDistributionS3ConfigOpaCredentialsWebIdentityCredentials) {
	*out = *in
	if in.AwsRegion != nil {
		in, out := &in.AwsRegion, &out.AwsRegion
		*out = new(string)
		**out = **in
	}
	if in.SessionName != nil {
		in, out := &in.SessionName, &out.SessionName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1BundleDistributionS3ConfigOpaCredentialsWebIdentityCredentials.
func (in *V1BundleDistributionS3ConfigOpaCredentialsWebIdentityCredentials) DeepCopy() *V1BundleDistributionS3ConfigOpaCredentialsWebIdentityCredentials {
	if in == nil {
		return nil
	}
	out := new(V1BundleDistributionS3ConfigOpaCredentialsWebIdentityCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1BundleRegistryConfig) DeepCopyInto(out *V1BundleRegistryConfig) {
	*out = *in
	if in.DistributionS3 != nil {
		in, out := &in.DistributionS3, &out.DistributionS3
		*out = new(V1BundleDistributionS3Config)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1BundleRegistryConfig.
func (in *V1BundleRegistryConfig) DeepCopy() *V1BundleRegistryConfig {
	if in == nil {
		return nil
	}
	out := new(V1BundleRegistryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1ColumnMapping) DeepCopyInto(out *V1ColumnMapping) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1ColumnMapping.
func (in *V1ColumnMapping) DeepCopy() *V1ColumnMapping {
	if in == nil {
		return nil
	}
	out := new(V1ColumnMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1DatasourceConfig) DeepCopyInto(out *V1DatasourceConfig) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(V1Status)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1DatasourceConfig.
func (in *V1DatasourceConfig) DeepCopy() *V1DatasourceConfig {
	if in == nil {
		return nil
	}
	out := new(V1DatasourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1EnforcementConfig) DeepCopyInto(out *V1EnforcementConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1EnforcementConfig.
func (in *V1EnforcementConfig) DeepCopy() *V1EnforcementConfig {
	if in == nil {
		return nil
	}
	out := new(V1EnforcementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1GitRepoConfig) DeepCopyInto(out *V1GitRepoConfig) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Reference != nil {
		in, out := &in.Reference, &out.Reference
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1GitRepoConfig.
func (in *V1GitRepoConfig) DeepCopy() *V1GitRepoConfig {
	if in == nil {
		return nil
	}
	out := new(V1GitRepoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1Module) DeepCopyInto(out *V1Module) {
	*out = *in
	if in.Placeholder != nil {
		in, out := &in.Placeholder, &out.Placeholder
		*out = new(bool)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = new(V1RuleCounts)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1Module.
func (in *V1Module) DeepCopy() *V1Module {
	if in == nil {
		return nil
	}
	out := new(V1Module)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1ObjectMeta) DeepCopyInto(out *V1ObjectMeta) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
	in.LastModifiedAt.DeepCopyInto(&out.LastModifiedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1ObjectMeta.
func (in *V1ObjectMeta) DeepCopy() *V1ObjectMeta {
	if in == nil {
		return nil
	}
	out := new(V1ObjectMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1PolicyConfig) DeepCopyInto(out *V1PolicyConfig) {
	*out = *in
	if in.Enforcement != nil {
		in, out := &in.Enforcement, &out.Enforcement
		*out = new(V1EnforcementConfig)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Modules != nil {
		in, out := &in.Modules, &out.Modules
		*out = make([]*V1Module, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(V1Module)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = new(V1RuleCounts)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1PolicyConfig.
func (in *V1PolicyConfig) DeepCopy() *V1PolicyConfig {
	if in == nil {
		return nil
	}
	out := new(V1PolicyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1ReasonMapping) DeepCopyInto(out *V1ReasonMapping) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1ReasonMapping.
func (in *V1ReasonMapping) DeepCopy() *V1ReasonMapping {
	if in == nil {
		return nil
	}
	out := new(V1ReasonMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1RoleBindingConfig) DeepCopyInto(out *V1RoleBindingConfig) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.RoleName != nil {
		in, out := &in.RoleName, &out.RoleName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1RoleBindingConfig.
func (in *V1RoleBindingConfig) DeepCopy() *V1RoleBindingConfig {
	if in == nil {
		return nil
	}
	out := new(V1RoleBindingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1RuleCounts) DeepCopyInto(out *V1RuleCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1RuleCounts.
func (in *V1RuleCounts) DeepCopy() *V1RuleCounts {
	if in == nil {
		return nil
	}
	out := new(V1RuleCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1RuleDecisionMappings) DeepCopyInto(out *V1RuleDecisionMappings) {
	*out = *in
	if in.Allowed != nil {
		in, out := &in.Allowed, &out.Allowed
		*out = new(V1AllowedMapping)
		(*in).DeepCopyInto(*out)
	}
	if in.Columns != nil {
		in, out := &in.Columns, &out.Columns
		*out = make([]*V1ColumnMapping, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(V1ColumnMapping)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(V1ReasonMapping)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1RuleDecisionMappings.
func (in *V1RuleDecisionMappings) DeepCopy() *V1RuleDecisionMappings {
	if in == nil {
		return nil
	}
	out := new(V1RuleDecisionMappings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1SourceControlConfig) DeepCopyInto(out *V1SourceControlConfig) {
	*out = *in
	if in.Origin != nil {
		in, out := &in.Origin, &out.Origin
		*out = new(V1GitRepoConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1SourceControlConfig.
func (in *V1SourceControlConfig) DeepCopy() *V1SourceControlConfig {
	if in == nil {
		return nil
	}
	out := new(V1SourceControlConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1Status) DeepCopyInto(out *V1Status) {
	*out = *in
	if in.Code != nil {
		in, out := &in.Code, &out.Code
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1Status.
func (in *V1Status) DeepCopy() *V1Status {
	if in == nil {
		return nil
	}
	out := new(V1Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1SystemConfigWarnings) DeepCopyInto(out *V1SystemConfigWarnings) {
	*out = *in
	if in.Code != nil {
		in, out := &in.Code, &out.Code
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1SystemConfigWarnings.
func (in *V1SystemConfigWarnings) DeepCopy() *V1SystemConfigWarnings {
	if in == nil {
		return nil
	}
	out := new(V1SystemConfigWarnings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1SystemDeploymentParameters) DeepCopyInto(out *V1SystemDeploymentParameters) {
	*out = *in
	if in.DenyOnOpaFail != nil {
		in, out := &in.DenyOnOpaFail, &out.DenyOnOpaFail
		*out = new(bool)
		**out = **in
	}
	if in.TrustedCaCerts != nil {
		in, out := &in.TrustedCaCerts, &out.TrustedCaCerts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1SystemDeploymentParameters.
func (in *V1SystemDeploymentParameters) DeepCopy() *V1SystemDeploymentParameters {
	if in == nil {
		return nil
	}
	out := new(V1SystemDeploymentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V1Token) DeepCopyInto(out *V1Token) {
	*out = *in
	if in.AllowPathPatterns != nil {
		in, out := &in.AllowPathPatterns, &out.AllowPathPatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Expires != nil {
		in, out := &in.Expires, &out.Expires
		*out = (*in).DeepCopy()
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(V1ObjectMeta)
		(*in).DeepCopyInto(*out)
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(string)
		**out = **in
	}
	if in.Uses != nil {
		in, out := &in.Uses, &out.Uses
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V1Token.
func (in *V1Token) DeepCopy() *V1Token {
	if in == nil {
		return nil
	}
	out := new(V1Token)
	in.DeepCopyInto(out)
	return out
}
