---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: default
type: Opaque
stringData:
  password: passw0rd
---
apiVersion: styra.crossplane.io/v1alpha1
kind: Secret
metadata:
  name: example-secret
spec:
  forProvider:
    name: my/secret/name
    description: "Hello world"
    secretRef:
      name: example-secret
      namespace: default
      key: password
  providerConfigRef:
    name: styra-provider
