apiVersion: styra.crossplane.io/v1alpha1
kind: DataSource
metadata:
  name: example-http
spec:
  forProvider:
    category: http
    type: pull
    onPremises: false
    http:
      url: http://sample-server.example
  providerConfigRef:
    name: styra-provider
