apiVersion: styra.crossplane.io/v1alpha1
kind: DataSource
metadata:
  name: example-ldap
spec:
  forProvider:
    category: ldap
    type: pull
    onPremises: false
    ldap:
      urls:
        - "http://sample-ldap.example"
  providerConfigRef:
    name: styra-provider
