apiVersion: styra.crossplane.io/v1alpha1
kind: DataSource
metadata:
  name: example-git-blame
spec:
  forProvider:
    category: git/blame
    type: pull
    onPremises: false
    gitBlame:
      url: example-git-repo
  providerConfigRef:
    name: styra-provider
